# Types for the parts of rbcl (libsodium's ristretto255) this package uses; rbcl ships none.

def crypto_core_ristretto255_from_hash(h: bytes) -> bytes: ...
def crypto_scalarmult_ristretto255(s: bytes, p: bytes) -> bytes: ...
