"""openagentlink: drive any agent linked over Open Agent Link (OAL).

Spec: https://openagent.link (spec/oal-0.1.md in NeboLoop/nebo-link).
"""

from .channel import (
    Authenticated,
    ChannelClosed,
    ChannelContext,
    Dialer,
    FrameChannel,
    SecureChannel,
    Socket,
    plaintext,
    websocket_dialer,
)
from .client import Agent, Client, Host, PermissionRequest, Session, Turn, connect
from .errors import (
    AgentError,
    AgentUnavailable,
    AlreadyAnswered,
    AttachmentFailed,
    Closed,
    ConnectionLost,
    HostOffline,
    InvalidParams,
    NotFound,
    NotOffered,
    NotPermitted,
    OALError,
    PairingRefused,
    TurnFailed,
    TurnInProgress,
    Unauthenticated,
    UnknownAgent,
    UnknownRequest,
    Unpaired,
    VersionMismatch,
)
from .events import (
    AgentChanged,
    Done,
    HostUpdate,
    ModeChanged,
    PermissionAsked,
    PermissionResolved,
    PlanUpdate,
    PresenceChanged,
    TextDelta,
    Thinking,
    ToolResult,
    ToolStart,
    ToolUpdate,
    TurnError,
    TurnEvent,
    Update,
    UsageReport,
    UserMessage,
)
from .identity import DeviceIdentity, HostIdentity, Identity, pair
from .types import PROTOCOL, Attachment

__version__ = "0.1.0"

__all__ = [
    "PROTOCOL",
    "Agent",
    "AgentChanged",
    "AgentError",
    "AgentUnavailable",
    "AlreadyAnswered",
    "Attachment",
    "AttachmentFailed",
    "Authenticated",
    "ChannelClosed",
    "ChannelContext",
    "Client",
    "Closed",
    "ConnectionLost",
    "DeviceIdentity",
    "Dialer",
    "Done",
    "FrameChannel",
    "Host",
    "HostIdentity",
    "HostOffline",
    "HostUpdate",
    "Identity",
    "InvalidParams",
    "ModeChanged",
    "NotFound",
    "NotOffered",
    "NotPermitted",
    "OALError",
    "PairingRefused",
    "PermissionAsked",
    "PermissionRequest",
    "PermissionResolved",
    "PlanUpdate",
    "PresenceChanged",
    "SecureChannel",
    "Session",
    "Socket",
    "TextDelta",
    "Thinking",
    "ToolResult",
    "ToolStart",
    "ToolUpdate",
    "Turn",
    "TurnError",
    "TurnEvent",
    "TurnFailed",
    "TurnInProgress",
    "Unauthenticated",
    "UnknownAgent",
    "UnknownRequest",
    "Unpaired",
    "Update",
    "UsageReport",
    "UserMessage",
    "VersionMismatch",
    "connect",
    "pair",
    "plaintext",
    "websocket_dialer",
]
